/* Automatically @generated by tree-sitter v0.25.5 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 10
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 87
#define ALIAS_COUNT 0
#define TOKEN_COUNT 80
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_line_comment = 2,
  sym_block_comment = 3,
  anon_sym_fn = 4,
  anon_sym_let = 5,
  anon_sym_mut = 6,
  anon_sym_const = 7,
  anon_sym_struct = 8,
  anon_sym_enum = 9,
  anon_sym_impl = 10,
  anon_sym_type = 11,
  anon_sym_distinct = 12,
  anon_sym_use = 13,
  anon_sym_include = 14,
  anon_sym_inline = 15,
  anon_sym_extern = 16,
  anon_sym_pub = 17,
  anon_sym_if = 18,
  anon_sym_else = 19,
  anon_sym_for = 20,
  anon_sym_in = 21,
  anon_sym_loop = 22,
  anon_sym_match = 23,
  anon_sym_break = 24,
  anon_sym_continue = 25,
  anon_sym_return = 26,
  anon_sym_is = 27,
  anon_sym_as = 28,
  anon_sym_self = 29,
  anon_sym_undefined = 30,
  anon_sym_true = 31,
  anon_sym_false = 32,
  aux_sym_number_token1 = 33,
  aux_sym_number_token2 = 34,
  aux_sym_number_token3 = 35,
  sym_string = 36,
  sym_char_literal = 37,
  anon_sym_DOT_DOT_EQ = 38,
  anon_sym_DOT_DOT = 39,
  anon_sym_LT_LT = 40,
  anon_sym_GT_GT = 41,
  anon_sym_EQ_EQ = 42,
  anon_sym_BANG_EQ = 43,
  anon_sym_LT_EQ = 44,
  anon_sym_GT_EQ = 45,
  anon_sym_PLUS_EQ = 46,
  anon_sym_DASH_EQ = 47,
  anon_sym_STAR_EQ = 48,
  anon_sym_SLASH_EQ = 49,
  anon_sym_PERCENT_EQ = 50,
  anon_sym_AMP_AMP = 51,
  anon_sym_PIPE_PIPE = 52,
  anon_sym_DASH_GT = 53,
  anon_sym_EQ_GT = 54,
  anon_sym_PLUS = 55,
  anon_sym_DASH = 56,
  anon_sym_STAR = 57,
  anon_sym_SLASH = 58,
  anon_sym_PERCENT = 59,
  anon_sym_AMP = 60,
  anon_sym_PIPE = 61,
  anon_sym_CARET = 62,
  anon_sym_TILDE = 63,
  anon_sym_BANG = 64,
  anon_sym_LT = 65,
  anon_sym_GT = 66,
  anon_sym_EQ = 67,
  anon_sym_LPAREN = 68,
  anon_sym_RPAREN = 69,
  anon_sym_LBRACE = 70,
  anon_sym_RBRACE = 71,
  anon_sym_LBRACK = 72,
  anon_sym_RBRACK = 73,
  anon_sym_COMMA = 74,
  anon_sym_SEMI = 75,
  anon_sym_COLON = 76,
  anon_sym_AT = 77,
  anon_sym_DOT = 78,
  anon_sym_QMARK = 79,
  sym_source_file = 80,
  sym_keyword = 81,
  sym_boolean = 82,
  sym_number = 83,
  sym_operator = 84,
  sym_punctuation = 85,
  aux_sym_source_file_repeat1 = 86,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [anon_sym_fn] = "fn",
  [anon_sym_let] = "let",
  [anon_sym_mut] = "mut",
  [anon_sym_const] = "const",
  [anon_sym_struct] = "struct",
  [anon_sym_enum] = "enum",
  [anon_sym_impl] = "impl",
  [anon_sym_type] = "type",
  [anon_sym_distinct] = "distinct",
  [anon_sym_use] = "use",
  [anon_sym_include] = "include",
  [anon_sym_inline] = "inline",
  [anon_sym_extern] = "extern",
  [anon_sym_pub] = "pub",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_for] = "for",
  [anon_sym_in] = "in",
  [anon_sym_loop] = "loop",
  [anon_sym_match] = "match",
  [anon_sym_break] = "break",
  [anon_sym_continue] = "continue",
  [anon_sym_return] = "return",
  [anon_sym_is] = "is",
  [anon_sym_as] = "as",
  [anon_sym_self] = "self",
  [anon_sym_undefined] = "undefined",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [aux_sym_number_token1] = "number_token1",
  [aux_sym_number_token2] = "number_token2",
  [aux_sym_number_token3] = "number_token3",
  [sym_string] = "string",
  [sym_char_literal] = "char_literal",
  [anon_sym_DOT_DOT_EQ] = "..=",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_LT_LT] = "<<",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_PLUS_EQ] = "+=",
  [anon_sym_DASH_EQ] = "-=",
  [anon_sym_STAR_EQ] = "*=",
  [anon_sym_SLASH_EQ] = "/=",
  [anon_sym_PERCENT_EQ] = "%=",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_AMP] = "&",
  [anon_sym_PIPE] = "|",
  [anon_sym_CARET] = "^",
  [anon_sym_TILDE] = "~",
  [anon_sym_BANG] = "!",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_EQ] = "=",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COMMA] = ",",
  [anon_sym_SEMI] = ";",
  [anon_sym_COLON] = ":",
  [anon_sym_AT] = "@",
  [anon_sym_DOT] = ".",
  [anon_sym_QMARK] = "\?",
  [sym_source_file] = "source_file",
  [sym_keyword] = "keyword",
  [sym_boolean] = "boolean",
  [sym_number] = "number",
  [sym_operator] = "operator",
  [sym_punctuation] = "punctuation",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_mut] = anon_sym_mut,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_impl] = anon_sym_impl,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_distinct] = anon_sym_distinct,
  [anon_sym_use] = anon_sym_use,
  [anon_sym_include] = anon_sym_include,
  [anon_sym_inline] = anon_sym_inline,
  [anon_sym_extern] = anon_sym_extern,
  [anon_sym_pub] = anon_sym_pub,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_loop] = anon_sym_loop,
  [anon_sym_match] = anon_sym_match,
  [anon_sym_break] = anon_sym_break,
  [anon_sym_continue] = anon_sym_continue,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_is] = anon_sym_is,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_self] = anon_sym_self,
  [anon_sym_undefined] = anon_sym_undefined,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [aux_sym_number_token2] = aux_sym_number_token2,
  [aux_sym_number_token3] = aux_sym_number_token3,
  [sym_string] = sym_string,
  [sym_char_literal] = sym_char_literal,
  [anon_sym_DOT_DOT_EQ] = anon_sym_DOT_DOT_EQ,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_LT_LT] = anon_sym_LT_LT,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_PLUS_EQ] = anon_sym_PLUS_EQ,
  [anon_sym_DASH_EQ] = anon_sym_DASH_EQ,
  [anon_sym_STAR_EQ] = anon_sym_STAR_EQ,
  [anon_sym_SLASH_EQ] = anon_sym_SLASH_EQ,
  [anon_sym_PERCENT_EQ] = anon_sym_PERCENT_EQ,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [sym_source_file] = sym_source_file,
  [sym_keyword] = sym_keyword,
  [sym_boolean] = sym_boolean,
  [sym_number] = sym_number,
  [sym_operator] = sym_operator,
  [sym_punctuation] = sym_punctuation,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mut] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_impl] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_distinct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_include] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_inline] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pub] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_loop] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_match] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_break] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_continue] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_is] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_self] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_undefined] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_char_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT_DOT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_punctuation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '!', 46,
        '"', 1,
        '%', 41,
        '&', 42,
        '\'', 5,
        '(', 50,
        ')', 51,
        '*', 39,
        '+', 37,
        ',', 56,
        '-', 38,
        '.', 60,
        '/', 40,
        '0', 15,
        ':', 58,
        ';', 57,
        '<', 47,
        '=', 49,
        '>', 48,
        '?', 61,
        '@', 59,
        '[', 54,
        ']', 55,
        '^', 44,
        '{', 52,
        '|', 43,
        '}', 53,
        '~', 45,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(18);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(12);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(2);
      END_STATE();
    case 6:
      if (lookahead == '0' ||
          lookahead == '1' ||
          lookahead == '_') ADVANCE(13);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '0' ||
          lookahead == '1' ||
          lookahead == '_') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_number_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_number_token3);
      if (lookahead == 'b') ADVANCE(6);
      if (lookahead == 'x') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_number_token3);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_char_literal);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DOT_DOT_EQ);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      if (lookahead == '=') ADVANCE(20);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_PLUS_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DASH_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_STAR_EQ);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_SLASH_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_PERCENT_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '=') ADVANCE(28);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '=') ADVANCE(29);
      if (lookahead == '>') ADVANCE(35);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '=') ADVANCE(30);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(11);
      if (lookahead == '=') ADVANCE(31);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead == '&') ADVANCE(33);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '|') ADVANCE(34);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(25);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '<') ADVANCE(22);
      if (lookahead == '=') ADVANCE(26);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(27);
      if (lookahead == '>') ADVANCE(23);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(24);
      if (lookahead == '>') ADVANCE(36);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(21);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'e', 5,
        'f', 6,
        'i', 7,
        'l', 8,
        'm', 9,
        'p', 10,
        'r', 11,
        's', 12,
        't', 13,
        'u', 14,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 2:
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 4:
      if (lookahead == 'i') ADVANCE(18);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(19);
      if (lookahead == 'n') ADVANCE(20);
      if (lookahead == 'x') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(22);
      if (lookahead == 'n') ADVANCE(23);
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 7:
      if (lookahead == 'f') ADVANCE(25);
      if (lookahead == 'm') ADVANCE(26);
      if (lookahead == 'n') ADVANCE(27);
      if (lookahead == 's') ADVANCE(28);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(29);
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(31);
      if (lookahead == 'u') ADVANCE(32);
      END_STATE();
    case 10:
      if (lookahead == 'u') ADVANCE(33);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(35);
      if (lookahead == 't') ADVANCE(36);
      END_STATE();
    case 13:
      if (lookahead == 'r') ADVANCE(37);
      if (lookahead == 'y') ADVANCE(38);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(39);
      if (lookahead == 's') ADVANCE(40);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(42);
      END_STATE();
    case 18:
      if (lookahead == 's') ADVANCE(43);
      END_STATE();
    case 19:
      if (lookahead == 's') ADVANCE(44);
      END_STATE();
    case 20:
      if (lookahead == 'u') ADVANCE(45);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(46);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(47);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(48);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 26:
      if (lookahead == 'p') ADVANCE(49);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_in);
      if (lookahead == 'c') ADVANCE(50);
      if (lookahead == 'l') ADVANCE(51);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_is);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(52);
      END_STATE();
    case 30:
      if (lookahead == 'o') ADVANCE(53);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(54);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(55);
      END_STATE();
    case 33:
      if (lookahead == 'b') ADVANCE(56);
      END_STATE();
    case 34:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 35:
      if (lookahead == 'l') ADVANCE(58);
      END_STATE();
    case 36:
      if (lookahead == 'r') ADVANCE(59);
      END_STATE();
    case 37:
      if (lookahead == 'u') ADVANCE(60);
      END_STATE();
    case 38:
      if (lookahead == 'p') ADVANCE(61);
      END_STATE();
    case 39:
      if (lookahead == 'd') ADVANCE(62);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(63);
      END_STATE();
    case 41:
      if (lookahead == 'a') ADVANCE(64);
      END_STATE();
    case 42:
      if (lookahead == 's') ADVANCE(65);
      if (lookahead == 't') ADVANCE(66);
      END_STATE();
    case 43:
      if (lookahead == 't') ADVANCE(67);
      END_STATE();
    case 44:
      if (lookahead == 'e') ADVANCE(68);
      END_STATE();
    case 45:
      if (lookahead == 'm') ADVANCE(69);
      END_STATE();
    case 46:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 47:
      if (lookahead == 's') ADVANCE(71);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 49:
      if (lookahead == 'l') ADVANCE(72);
      END_STATE();
    case 50:
      if (lookahead == 'l') ADVANCE(73);
      END_STATE();
    case 51:
      if (lookahead == 'i') ADVANCE(74);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 53:
      if (lookahead == 'p') ADVANCE(75);
      END_STATE();
    case 54:
      if (lookahead == 'c') ADVANCE(76);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_mut);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_pub);
      END_STATE();
    case 57:
      if (lookahead == 'u') ADVANCE(77);
      END_STATE();
    case 58:
      if (lookahead == 'f') ADVANCE(78);
      END_STATE();
    case 59:
      if (lookahead == 'u') ADVANCE(79);
      END_STATE();
    case 60:
      if (lookahead == 'e') ADVANCE(80);
      END_STATE();
    case 61:
      if (lookahead == 'e') ADVANCE(81);
      END_STATE();
    case 62:
      if (lookahead == 'e') ADVANCE(82);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_use);
      END_STATE();
    case 64:
      if (lookahead == 'k') ADVANCE(83);
      END_STATE();
    case 65:
      if (lookahead == 't') ADVANCE(84);
      END_STATE();
    case 66:
      if (lookahead == 'i') ADVANCE(85);
      END_STATE();
    case 67:
      if (lookahead == 'i') ADVANCE(86);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 70:
      if (lookahead == 'r') ADVANCE(87);
      END_STATE();
    case 71:
      if (lookahead == 'e') ADVANCE(88);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_impl);
      END_STATE();
    case 73:
      if (lookahead == 'u') ADVANCE(89);
      END_STATE();
    case 74:
      if (lookahead == 'n') ADVANCE(90);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_loop);
      END_STATE();
    case 76:
      if (lookahead == 'h') ADVANCE(91);
      END_STATE();
    case 77:
      if (lookahead == 'r') ADVANCE(92);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_self);
      END_STATE();
    case 79:
      if (lookahead == 'c') ADVANCE(93);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 82:
      if (lookahead == 'f') ADVANCE(94);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_break);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 85:
      if (lookahead == 'n') ADVANCE(95);
      END_STATE();
    case 86:
      if (lookahead == 'n') ADVANCE(96);
      END_STATE();
    case 87:
      if (lookahead == 'n') ADVANCE(97);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 89:
      if (lookahead == 'd') ADVANCE(98);
      END_STATE();
    case 90:
      if (lookahead == 'e') ADVANCE(99);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_match);
      END_STATE();
    case 92:
      if (lookahead == 'n') ADVANCE(100);
      END_STATE();
    case 93:
      if (lookahead == 't') ADVANCE(101);
      END_STATE();
    case 94:
      if (lookahead == 'i') ADVANCE(102);
      END_STATE();
    case 95:
      if (lookahead == 'u') ADVANCE(103);
      END_STATE();
    case 96:
      if (lookahead == 'c') ADVANCE(104);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_extern);
      END_STATE();
    case 98:
      if (lookahead == 'e') ADVANCE(105);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_inline);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 102:
      if (lookahead == 'n') ADVANCE(106);
      END_STATE();
    case 103:
      if (lookahead == 'e') ADVANCE(107);
      END_STATE();
    case 104:
      if (lookahead == 't') ADVANCE(108);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_include);
      END_STATE();
    case 106:
      if (lookahead == 'e') ADVANCE(109);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_continue);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_distinct);
      END_STATE();
    case 109:
      if (lookahead == 'd') ADVANCE(110);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_undefined);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_mut] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_impl] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_distinct] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_include] = ACTIONS(1),
    [anon_sym_inline] = ACTIONS(1),
    [anon_sym_extern] = ACTIONS(1),
    [anon_sym_pub] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_loop] = ACTIONS(1),
    [anon_sym_match] = ACTIONS(1),
    [anon_sym_break] = ACTIONS(1),
    [anon_sym_continue] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_is] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_self] = ACTIONS(1),
    [anon_sym_undefined] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [aux_sym_number_token2] = ACTIONS(1),
    [aux_sym_number_token3] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_char_literal] = ACTIONS(1),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_LT_LT] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_PLUS_EQ] = ACTIONS(1),
    [anon_sym_DASH_EQ] = ACTIONS(1),
    [anon_sym_STAR_EQ] = ACTIONS(1),
    [anon_sym_SLASH_EQ] = ACTIONS(1),
    [anon_sym_PERCENT_EQ] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(9),
    [sym_keyword] = STATE(2),
    [sym_boolean] = STATE(2),
    [sym_number] = STATE(2),
    [sym_operator] = STATE(2),
    [sym_punctuation] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_mut] = ACTIONS(9),
    [anon_sym_const] = ACTIONS(9),
    [anon_sym_struct] = ACTIONS(9),
    [anon_sym_enum] = ACTIONS(9),
    [anon_sym_impl] = ACTIONS(9),
    [anon_sym_type] = ACTIONS(9),
    [anon_sym_distinct] = ACTIONS(9),
    [anon_sym_use] = ACTIONS(9),
    [anon_sym_include] = ACTIONS(9),
    [anon_sym_inline] = ACTIONS(9),
    [anon_sym_extern] = ACTIONS(9),
    [anon_sym_pub] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_else] = ACTIONS(9),
    [anon_sym_for] = ACTIONS(9),
    [anon_sym_in] = ACTIONS(9),
    [anon_sym_loop] = ACTIONS(9),
    [anon_sym_match] = ACTIONS(9),
    [anon_sym_break] = ACTIONS(9),
    [anon_sym_continue] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(9),
    [anon_sym_is] = ACTIONS(9),
    [anon_sym_as] = ACTIONS(9),
    [anon_sym_self] = ACTIONS(9),
    [anon_sym_undefined] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [aux_sym_number_token1] = ACTIONS(13),
    [aux_sym_number_token2] = ACTIONS(13),
    [aux_sym_number_token3] = ACTIONS(15),
    [sym_string] = ACTIONS(17),
    [sym_char_literal] = ACTIONS(17),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(19),
    [anon_sym_DOT_DOT] = ACTIONS(21),
    [anon_sym_LT_LT] = ACTIONS(19),
    [anon_sym_GT_GT] = ACTIONS(19),
    [anon_sym_EQ_EQ] = ACTIONS(19),
    [anon_sym_BANG_EQ] = ACTIONS(19),
    [anon_sym_LT_EQ] = ACTIONS(19),
    [anon_sym_GT_EQ] = ACTIONS(19),
    [anon_sym_PLUS_EQ] = ACTIONS(19),
    [anon_sym_DASH_EQ] = ACTIONS(19),
    [anon_sym_STAR_EQ] = ACTIONS(19),
    [anon_sym_SLASH_EQ] = ACTIONS(19),
    [anon_sym_PERCENT_EQ] = ACTIONS(19),
    [anon_sym_AMP_AMP] = ACTIONS(19),
    [anon_sym_PIPE_PIPE] = ACTIONS(19),
    [anon_sym_DASH_GT] = ACTIONS(19),
    [anon_sym_EQ_GT] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(21),
    [anon_sym_PERCENT] = ACTIONS(21),
    [anon_sym_AMP] = ACTIONS(21),
    [anon_sym_PIPE] = ACTIONS(21),
    [anon_sym_CARET] = ACTIONS(19),
    [anon_sym_TILDE] = ACTIONS(19),
    [anon_sym_BANG] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(21),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_RBRACK] = ACTIONS(23),
    [anon_sym_COMMA] = ACTIONS(23),
    [anon_sym_SEMI] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(23),
    [anon_sym_AT] = ACTIONS(23),
    [anon_sym_DOT] = ACTIONS(25),
    [anon_sym_QMARK] = ACTIONS(23),
  },
  [STATE(2)] = {
    [sym_keyword] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_number] = STATE(3),
    [sym_operator] = STATE(3),
    [sym_punctuation] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_identifier] = ACTIONS(29),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_mut] = ACTIONS(9),
    [anon_sym_const] = ACTIONS(9),
    [anon_sym_struct] = ACTIONS(9),
    [anon_sym_enum] = ACTIONS(9),
    [anon_sym_impl] = ACTIONS(9),
    [anon_sym_type] = ACTIONS(9),
    [anon_sym_distinct] = ACTIONS(9),
    [anon_sym_use] = ACTIONS(9),
    [anon_sym_include] = ACTIONS(9),
    [anon_sym_inline] = ACTIONS(9),
    [anon_sym_extern] = ACTIONS(9),
    [anon_sym_pub] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_else] = ACTIONS(9),
    [anon_sym_for] = ACTIONS(9),
    [anon_sym_in] = ACTIONS(9),
    [anon_sym_loop] = ACTIONS(9),
    [anon_sym_match] = ACTIONS(9),
    [anon_sym_break] = ACTIONS(9),
    [anon_sym_continue] = ACTIONS(9),
    [anon_sym_return] = ACTIONS(9),
    [anon_sym_is] = ACTIONS(9),
    [anon_sym_as] = ACTIONS(9),
    [anon_sym_self] = ACTIONS(9),
    [anon_sym_undefined] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [aux_sym_number_token1] = ACTIONS(13),
    [aux_sym_number_token2] = ACTIONS(13),
    [aux_sym_number_token3] = ACTIONS(15),
    [sym_string] = ACTIONS(31),
    [sym_char_literal] = ACTIONS(31),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(19),
    [anon_sym_DOT_DOT] = ACTIONS(21),
    [anon_sym_LT_LT] = ACTIONS(19),
    [anon_sym_GT_GT] = ACTIONS(19),
    [anon_sym_EQ_EQ] = ACTIONS(19),
    [anon_sym_BANG_EQ] = ACTIONS(19),
    [anon_sym_LT_EQ] = ACTIONS(19),
    [anon_sym_GT_EQ] = ACTIONS(19),
    [anon_sym_PLUS_EQ] = ACTIONS(19),
    [anon_sym_DASH_EQ] = ACTIONS(19),
    [anon_sym_STAR_EQ] = ACTIONS(19),
    [anon_sym_SLASH_EQ] = ACTIONS(19),
    [anon_sym_PERCENT_EQ] = ACTIONS(19),
    [anon_sym_AMP_AMP] = ACTIONS(19),
    [anon_sym_PIPE_PIPE] = ACTIONS(19),
    [anon_sym_DASH_GT] = ACTIONS(19),
    [anon_sym_EQ_GT] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(21),
    [anon_sym_PERCENT] = ACTIONS(21),
    [anon_sym_AMP] = ACTIONS(21),
    [anon_sym_PIPE] = ACTIONS(21),
    [anon_sym_CARET] = ACTIONS(19),
    [anon_sym_TILDE] = ACTIONS(19),
    [anon_sym_BANG] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(21),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_RBRACK] = ACTIONS(23),
    [anon_sym_COMMA] = ACTIONS(23),
    [anon_sym_SEMI] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(23),
    [anon_sym_AT] = ACTIONS(23),
    [anon_sym_DOT] = ACTIONS(25),
    [anon_sym_QMARK] = ACTIONS(23),
  },
  [STATE(3)] = {
    [sym_keyword] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_number] = STATE(3),
    [sym_operator] = STATE(3),
    [sym_punctuation] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym_identifier] = ACTIONS(35),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(38),
    [anon_sym_let] = ACTIONS(38),
    [anon_sym_mut] = ACTIONS(38),
    [anon_sym_const] = ACTIONS(38),
    [anon_sym_struct] = ACTIONS(38),
    [anon_sym_enum] = ACTIONS(38),
    [anon_sym_impl] = ACTIONS(38),
    [anon_sym_type] = ACTIONS(38),
    [anon_sym_distinct] = ACTIONS(38),
    [anon_sym_use] = ACTIONS(38),
    [anon_sym_include] = ACTIONS(38),
    [anon_sym_inline] = ACTIONS(38),
    [anon_sym_extern] = ACTIONS(38),
    [anon_sym_pub] = ACTIONS(38),
    [anon_sym_if] = ACTIONS(38),
    [anon_sym_else] = ACTIONS(38),
    [anon_sym_for] = ACTIONS(38),
    [anon_sym_in] = ACTIONS(38),
    [anon_sym_loop] = ACTIONS(38),
    [anon_sym_match] = ACTIONS(38),
    [anon_sym_break] = ACTIONS(38),
    [anon_sym_continue] = ACTIONS(38),
    [anon_sym_return] = ACTIONS(38),
    [anon_sym_is] = ACTIONS(38),
    [anon_sym_as] = ACTIONS(38),
    [anon_sym_self] = ACTIONS(38),
    [anon_sym_undefined] = ACTIONS(38),
    [anon_sym_true] = ACTIONS(41),
    [anon_sym_false] = ACTIONS(41),
    [aux_sym_number_token1] = ACTIONS(44),
    [aux_sym_number_token2] = ACTIONS(44),
    [aux_sym_number_token3] = ACTIONS(47),
    [sym_string] = ACTIONS(50),
    [sym_char_literal] = ACTIONS(50),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(53),
    [anon_sym_DOT_DOT] = ACTIONS(56),
    [anon_sym_LT_LT] = ACTIONS(53),
    [anon_sym_GT_GT] = ACTIONS(53),
    [anon_sym_EQ_EQ] = ACTIONS(53),
    [anon_sym_BANG_EQ] = ACTIONS(53),
    [anon_sym_LT_EQ] = ACTIONS(53),
    [anon_sym_GT_EQ] = ACTIONS(53),
    [anon_sym_PLUS_EQ] = ACTIONS(53),
    [anon_sym_DASH_EQ] = ACTIONS(53),
    [anon_sym_STAR_EQ] = ACTIONS(53),
    [anon_sym_SLASH_EQ] = ACTIONS(53),
    [anon_sym_PERCENT_EQ] = ACTIONS(53),
    [anon_sym_AMP_AMP] = ACTIONS(53),
    [anon_sym_PIPE_PIPE] = ACTIONS(53),
    [anon_sym_DASH_GT] = ACTIONS(53),
    [anon_sym_EQ_GT] = ACTIONS(53),
    [anon_sym_PLUS] = ACTIONS(56),
    [anon_sym_DASH] = ACTIONS(56),
    [anon_sym_STAR] = ACTIONS(56),
    [anon_sym_SLASH] = ACTIONS(56),
    [anon_sym_PERCENT] = ACTIONS(56),
    [anon_sym_AMP] = ACTIONS(56),
    [anon_sym_PIPE] = ACTIONS(56),
    [anon_sym_CARET] = ACTIONS(53),
    [anon_sym_TILDE] = ACTIONS(53),
    [anon_sym_BANG] = ACTIONS(56),
    [anon_sym_LT] = ACTIONS(56),
    [anon_sym_GT] = ACTIONS(56),
    [anon_sym_EQ] = ACTIONS(56),
    [anon_sym_LPAREN] = ACTIONS(59),
    [anon_sym_RPAREN] = ACTIONS(59),
    [anon_sym_LBRACE] = ACTIONS(59),
    [anon_sym_RBRACE] = ACTIONS(59),
    [anon_sym_LBRACK] = ACTIONS(59),
    [anon_sym_RBRACK] = ACTIONS(59),
    [anon_sym_COMMA] = ACTIONS(59),
    [anon_sym_SEMI] = ACTIONS(59),
    [anon_sym_COLON] = ACTIONS(59),
    [anon_sym_AT] = ACTIONS(59),
    [anon_sym_DOT] = ACTIONS(62),
    [anon_sym_QMARK] = ACTIONS(59),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(65),
    [sym_identifier] = ACTIONS(67),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(67),
    [anon_sym_let] = ACTIONS(67),
    [anon_sym_mut] = ACTIONS(67),
    [anon_sym_const] = ACTIONS(67),
    [anon_sym_struct] = ACTIONS(67),
    [anon_sym_enum] = ACTIONS(67),
    [anon_sym_impl] = ACTIONS(67),
    [anon_sym_type] = ACTIONS(67),
    [anon_sym_distinct] = ACTIONS(67),
    [anon_sym_use] = ACTIONS(67),
    [anon_sym_include] = ACTIONS(67),
    [anon_sym_inline] = ACTIONS(67),
    [anon_sym_extern] = ACTIONS(67),
    [anon_sym_pub] = ACTIONS(67),
    [anon_sym_if] = ACTIONS(67),
    [anon_sym_else] = ACTIONS(67),
    [anon_sym_for] = ACTIONS(67),
    [anon_sym_in] = ACTIONS(67),
    [anon_sym_loop] = ACTIONS(67),
    [anon_sym_match] = ACTIONS(67),
    [anon_sym_break] = ACTIONS(67),
    [anon_sym_continue] = ACTIONS(67),
    [anon_sym_return] = ACTIONS(67),
    [anon_sym_is] = ACTIONS(67),
    [anon_sym_as] = ACTIONS(67),
    [anon_sym_self] = ACTIONS(67),
    [anon_sym_undefined] = ACTIONS(67),
    [anon_sym_true] = ACTIONS(67),
    [anon_sym_false] = ACTIONS(67),
    [aux_sym_number_token1] = ACTIONS(65),
    [aux_sym_number_token2] = ACTIONS(65),
    [aux_sym_number_token3] = ACTIONS(67),
    [sym_string] = ACTIONS(65),
    [sym_char_literal] = ACTIONS(65),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(65),
    [anon_sym_DOT_DOT] = ACTIONS(67),
    [anon_sym_LT_LT] = ACTIONS(65),
    [anon_sym_GT_GT] = ACTIONS(65),
    [anon_sym_EQ_EQ] = ACTIONS(65),
    [anon_sym_BANG_EQ] = ACTIONS(65),
    [anon_sym_LT_EQ] = ACTIONS(65),
    [anon_sym_GT_EQ] = ACTIONS(65),
    [anon_sym_PLUS_EQ] = ACTIONS(65),
    [anon_sym_DASH_EQ] = ACTIONS(65),
    [anon_sym_STAR_EQ] = ACTIONS(65),
    [anon_sym_SLASH_EQ] = ACTIONS(65),
    [anon_sym_PERCENT_EQ] = ACTIONS(65),
    [anon_sym_AMP_AMP] = ACTIONS(65),
    [anon_sym_PIPE_PIPE] = ACTIONS(65),
    [anon_sym_DASH_GT] = ACTIONS(65),
    [anon_sym_EQ_GT] = ACTIONS(65),
    [anon_sym_PLUS] = ACTIONS(67),
    [anon_sym_DASH] = ACTIONS(67),
    [anon_sym_STAR] = ACTIONS(67),
    [anon_sym_SLASH] = ACTIONS(67),
    [anon_sym_PERCENT] = ACTIONS(67),
    [anon_sym_AMP] = ACTIONS(67),
    [anon_sym_PIPE] = ACTIONS(67),
    [anon_sym_CARET] = ACTIONS(65),
    [anon_sym_TILDE] = ACTIONS(65),
    [anon_sym_BANG] = ACTIONS(67),
    [anon_sym_LT] = ACTIONS(67),
    [anon_sym_GT] = ACTIONS(67),
    [anon_sym_EQ] = ACTIONS(67),
    [anon_sym_LPAREN] = ACTIONS(65),
    [anon_sym_RPAREN] = ACTIONS(65),
    [anon_sym_LBRACE] = ACTIONS(65),
    [anon_sym_RBRACE] = ACTIONS(65),
    [anon_sym_LBRACK] = ACTIONS(65),
    [anon_sym_RBRACK] = ACTIONS(65),
    [anon_sym_COMMA] = ACTIONS(65),
    [anon_sym_SEMI] = ACTIONS(65),
    [anon_sym_COLON] = ACTIONS(65),
    [anon_sym_AT] = ACTIONS(65),
    [anon_sym_DOT] = ACTIONS(67),
    [anon_sym_QMARK] = ACTIONS(65),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(69),
    [sym_identifier] = ACTIONS(71),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(71),
    [anon_sym_let] = ACTIONS(71),
    [anon_sym_mut] = ACTIONS(71),
    [anon_sym_const] = ACTIONS(71),
    [anon_sym_struct] = ACTIONS(71),
    [anon_sym_enum] = ACTIONS(71),
    [anon_sym_impl] = ACTIONS(71),
    [anon_sym_type] = ACTIONS(71),
    [anon_sym_distinct] = ACTIONS(71),
    [anon_sym_use] = ACTIONS(71),
    [anon_sym_include] = ACTIONS(71),
    [anon_sym_inline] = ACTIONS(71),
    [anon_sym_extern] = ACTIONS(71),
    [anon_sym_pub] = ACTIONS(71),
    [anon_sym_if] = ACTIONS(71),
    [anon_sym_else] = ACTIONS(71),
    [anon_sym_for] = ACTIONS(71),
    [anon_sym_in] = ACTIONS(71),
    [anon_sym_loop] = ACTIONS(71),
    [anon_sym_match] = ACTIONS(71),
    [anon_sym_break] = ACTIONS(71),
    [anon_sym_continue] = ACTIONS(71),
    [anon_sym_return] = ACTIONS(71),
    [anon_sym_is] = ACTIONS(71),
    [anon_sym_as] = ACTIONS(71),
    [anon_sym_self] = ACTIONS(71),
    [anon_sym_undefined] = ACTIONS(71),
    [anon_sym_true] = ACTIONS(71),
    [anon_sym_false] = ACTIONS(71),
    [aux_sym_number_token1] = ACTIONS(69),
    [aux_sym_number_token2] = ACTIONS(69),
    [aux_sym_number_token3] = ACTIONS(71),
    [sym_string] = ACTIONS(69),
    [sym_char_literal] = ACTIONS(69),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(69),
    [anon_sym_DOT_DOT] = ACTIONS(71),
    [anon_sym_LT_LT] = ACTIONS(69),
    [anon_sym_GT_GT] = ACTIONS(69),
    [anon_sym_EQ_EQ] = ACTIONS(69),
    [anon_sym_BANG_EQ] = ACTIONS(69),
    [anon_sym_LT_EQ] = ACTIONS(69),
    [anon_sym_GT_EQ] = ACTIONS(69),
    [anon_sym_PLUS_EQ] = ACTIONS(69),
    [anon_sym_DASH_EQ] = ACTIONS(69),
    [anon_sym_STAR_EQ] = ACTIONS(69),
    [anon_sym_SLASH_EQ] = ACTIONS(69),
    [anon_sym_PERCENT_EQ] = ACTIONS(69),
    [anon_sym_AMP_AMP] = ACTIONS(69),
    [anon_sym_PIPE_PIPE] = ACTIONS(69),
    [anon_sym_DASH_GT] = ACTIONS(69),
    [anon_sym_EQ_GT] = ACTIONS(69),
    [anon_sym_PLUS] = ACTIONS(71),
    [anon_sym_DASH] = ACTIONS(71),
    [anon_sym_STAR] = ACTIONS(71),
    [anon_sym_SLASH] = ACTIONS(71),
    [anon_sym_PERCENT] = ACTIONS(71),
    [anon_sym_AMP] = ACTIONS(71),
    [anon_sym_PIPE] = ACTIONS(71),
    [anon_sym_CARET] = ACTIONS(69),
    [anon_sym_TILDE] = ACTIONS(69),
    [anon_sym_BANG] = ACTIONS(71),
    [anon_sym_LT] = ACTIONS(71),
    [anon_sym_GT] = ACTIONS(71),
    [anon_sym_EQ] = ACTIONS(71),
    [anon_sym_LPAREN] = ACTIONS(69),
    [anon_sym_RPAREN] = ACTIONS(69),
    [anon_sym_LBRACE] = ACTIONS(69),
    [anon_sym_RBRACE] = ACTIONS(69),
    [anon_sym_LBRACK] = ACTIONS(69),
    [anon_sym_RBRACK] = ACTIONS(69),
    [anon_sym_COMMA] = ACTIONS(69),
    [anon_sym_SEMI] = ACTIONS(69),
    [anon_sym_COLON] = ACTIONS(69),
    [anon_sym_AT] = ACTIONS(69),
    [anon_sym_DOT] = ACTIONS(71),
    [anon_sym_QMARK] = ACTIONS(69),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(73),
    [sym_identifier] = ACTIONS(75),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(75),
    [anon_sym_let] = ACTIONS(75),
    [anon_sym_mut] = ACTIONS(75),
    [anon_sym_const] = ACTIONS(75),
    [anon_sym_struct] = ACTIONS(75),
    [anon_sym_enum] = ACTIONS(75),
    [anon_sym_impl] = ACTIONS(75),
    [anon_sym_type] = ACTIONS(75),
    [anon_sym_distinct] = ACTIONS(75),
    [anon_sym_use] = ACTIONS(75),
    [anon_sym_include] = ACTIONS(75),
    [anon_sym_inline] = ACTIONS(75),
    [anon_sym_extern] = ACTIONS(75),
    [anon_sym_pub] = ACTIONS(75),
    [anon_sym_if] = ACTIONS(75),
    [anon_sym_else] = ACTIONS(75),
    [anon_sym_for] = ACTIONS(75),
    [anon_sym_in] = ACTIONS(75),
    [anon_sym_loop] = ACTIONS(75),
    [anon_sym_match] = ACTIONS(75),
    [anon_sym_break] = ACTIONS(75),
    [anon_sym_continue] = ACTIONS(75),
    [anon_sym_return] = ACTIONS(75),
    [anon_sym_is] = ACTIONS(75),
    [anon_sym_as] = ACTIONS(75),
    [anon_sym_self] = ACTIONS(75),
    [anon_sym_undefined] = ACTIONS(75),
    [anon_sym_true] = ACTIONS(75),
    [anon_sym_false] = ACTIONS(75),
    [aux_sym_number_token1] = ACTIONS(73),
    [aux_sym_number_token2] = ACTIONS(73),
    [aux_sym_number_token3] = ACTIONS(75),
    [sym_string] = ACTIONS(73),
    [sym_char_literal] = ACTIONS(73),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(73),
    [anon_sym_DOT_DOT] = ACTIONS(75),
    [anon_sym_LT_LT] = ACTIONS(73),
    [anon_sym_GT_GT] = ACTIONS(73),
    [anon_sym_EQ_EQ] = ACTIONS(73),
    [anon_sym_BANG_EQ] = ACTIONS(73),
    [anon_sym_LT_EQ] = ACTIONS(73),
    [anon_sym_GT_EQ] = ACTIONS(73),
    [anon_sym_PLUS_EQ] = ACTIONS(73),
    [anon_sym_DASH_EQ] = ACTIONS(73),
    [anon_sym_STAR_EQ] = ACTIONS(73),
    [anon_sym_SLASH_EQ] = ACTIONS(73),
    [anon_sym_PERCENT_EQ] = ACTIONS(73),
    [anon_sym_AMP_AMP] = ACTIONS(73),
    [anon_sym_PIPE_PIPE] = ACTIONS(73),
    [anon_sym_DASH_GT] = ACTIONS(73),
    [anon_sym_EQ_GT] = ACTIONS(73),
    [anon_sym_PLUS] = ACTIONS(75),
    [anon_sym_DASH] = ACTIONS(75),
    [anon_sym_STAR] = ACTIONS(75),
    [anon_sym_SLASH] = ACTIONS(75),
    [anon_sym_PERCENT] = ACTIONS(75),
    [anon_sym_AMP] = ACTIONS(75),
    [anon_sym_PIPE] = ACTIONS(75),
    [anon_sym_CARET] = ACTIONS(73),
    [anon_sym_TILDE] = ACTIONS(73),
    [anon_sym_BANG] = ACTIONS(75),
    [anon_sym_LT] = ACTIONS(75),
    [anon_sym_GT] = ACTIONS(75),
    [anon_sym_EQ] = ACTIONS(75),
    [anon_sym_LPAREN] = ACTIONS(73),
    [anon_sym_RPAREN] = ACTIONS(73),
    [anon_sym_LBRACE] = ACTIONS(73),
    [anon_sym_RBRACE] = ACTIONS(73),
    [anon_sym_LBRACK] = ACTIONS(73),
    [anon_sym_RBRACK] = ACTIONS(73),
    [anon_sym_COMMA] = ACTIONS(73),
    [anon_sym_SEMI] = ACTIONS(73),
    [anon_sym_COLON] = ACTIONS(73),
    [anon_sym_AT] = ACTIONS(73),
    [anon_sym_DOT] = ACTIONS(75),
    [anon_sym_QMARK] = ACTIONS(73),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(77),
    [sym_identifier] = ACTIONS(79),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(79),
    [anon_sym_let] = ACTIONS(79),
    [anon_sym_mut] = ACTIONS(79),
    [anon_sym_const] = ACTIONS(79),
    [anon_sym_struct] = ACTIONS(79),
    [anon_sym_enum] = ACTIONS(79),
    [anon_sym_impl] = ACTIONS(79),
    [anon_sym_type] = ACTIONS(79),
    [anon_sym_distinct] = ACTIONS(79),
    [anon_sym_use] = ACTIONS(79),
    [anon_sym_include] = ACTIONS(79),
    [anon_sym_inline] = ACTIONS(79),
    [anon_sym_extern] = ACTIONS(79),
    [anon_sym_pub] = ACTIONS(79),
    [anon_sym_if] = ACTIONS(79),
    [anon_sym_else] = ACTIONS(79),
    [anon_sym_for] = ACTIONS(79),
    [anon_sym_in] = ACTIONS(79),
    [anon_sym_loop] = ACTIONS(79),
    [anon_sym_match] = ACTIONS(79),
    [anon_sym_break] = ACTIONS(79),
    [anon_sym_continue] = ACTIONS(79),
    [anon_sym_return] = ACTIONS(79),
    [anon_sym_is] = ACTIONS(79),
    [anon_sym_as] = ACTIONS(79),
    [anon_sym_self] = ACTIONS(79),
    [anon_sym_undefined] = ACTIONS(79),
    [anon_sym_true] = ACTIONS(79),
    [anon_sym_false] = ACTIONS(79),
    [aux_sym_number_token1] = ACTIONS(77),
    [aux_sym_number_token2] = ACTIONS(77),
    [aux_sym_number_token3] = ACTIONS(79),
    [sym_string] = ACTIONS(77),
    [sym_char_literal] = ACTIONS(77),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(77),
    [anon_sym_DOT_DOT] = ACTIONS(79),
    [anon_sym_LT_LT] = ACTIONS(77),
    [anon_sym_GT_GT] = ACTIONS(77),
    [anon_sym_EQ_EQ] = ACTIONS(77),
    [anon_sym_BANG_EQ] = ACTIONS(77),
    [anon_sym_LT_EQ] = ACTIONS(77),
    [anon_sym_GT_EQ] = ACTIONS(77),
    [anon_sym_PLUS_EQ] = ACTIONS(77),
    [anon_sym_DASH_EQ] = ACTIONS(77),
    [anon_sym_STAR_EQ] = ACTIONS(77),
    [anon_sym_SLASH_EQ] = ACTIONS(77),
    [anon_sym_PERCENT_EQ] = ACTIONS(77),
    [anon_sym_AMP_AMP] = ACTIONS(77),
    [anon_sym_PIPE_PIPE] = ACTIONS(77),
    [anon_sym_DASH_GT] = ACTIONS(77),
    [anon_sym_EQ_GT] = ACTIONS(77),
    [anon_sym_PLUS] = ACTIONS(79),
    [anon_sym_DASH] = ACTIONS(79),
    [anon_sym_STAR] = ACTIONS(79),
    [anon_sym_SLASH] = ACTIONS(79),
    [anon_sym_PERCENT] = ACTIONS(79),
    [anon_sym_AMP] = ACTIONS(79),
    [anon_sym_PIPE] = ACTIONS(79),
    [anon_sym_CARET] = ACTIONS(77),
    [anon_sym_TILDE] = ACTIONS(77),
    [anon_sym_BANG] = ACTIONS(79),
    [anon_sym_LT] = ACTIONS(79),
    [anon_sym_GT] = ACTIONS(79),
    [anon_sym_EQ] = ACTIONS(79),
    [anon_sym_LPAREN] = ACTIONS(77),
    [anon_sym_RPAREN] = ACTIONS(77),
    [anon_sym_LBRACE] = ACTIONS(77),
    [anon_sym_RBRACE] = ACTIONS(77),
    [anon_sym_LBRACK] = ACTIONS(77),
    [anon_sym_RBRACK] = ACTIONS(77),
    [anon_sym_COMMA] = ACTIONS(77),
    [anon_sym_SEMI] = ACTIONS(77),
    [anon_sym_COLON] = ACTIONS(77),
    [anon_sym_AT] = ACTIONS(77),
    [anon_sym_DOT] = ACTIONS(79),
    [anon_sym_QMARK] = ACTIONS(77),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(81),
    [sym_identifier] = ACTIONS(83),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(83),
    [anon_sym_let] = ACTIONS(83),
    [anon_sym_mut] = ACTIONS(83),
    [anon_sym_const] = ACTIONS(83),
    [anon_sym_struct] = ACTIONS(83),
    [anon_sym_enum] = ACTIONS(83),
    [anon_sym_impl] = ACTIONS(83),
    [anon_sym_type] = ACTIONS(83),
    [anon_sym_distinct] = ACTIONS(83),
    [anon_sym_use] = ACTIONS(83),
    [anon_sym_include] = ACTIONS(83),
    [anon_sym_inline] = ACTIONS(83),
    [anon_sym_extern] = ACTIONS(83),
    [anon_sym_pub] = ACTIONS(83),
    [anon_sym_if] = ACTIONS(83),
    [anon_sym_else] = ACTIONS(83),
    [anon_sym_for] = ACTIONS(83),
    [anon_sym_in] = ACTIONS(83),
    [anon_sym_loop] = ACTIONS(83),
    [anon_sym_match] = ACTIONS(83),
    [anon_sym_break] = ACTIONS(83),
    [anon_sym_continue] = ACTIONS(83),
    [anon_sym_return] = ACTIONS(83),
    [anon_sym_is] = ACTIONS(83),
    [anon_sym_as] = ACTIONS(83),
    [anon_sym_self] = ACTIONS(83),
    [anon_sym_undefined] = ACTIONS(83),
    [anon_sym_true] = ACTIONS(83),
    [anon_sym_false] = ACTIONS(83),
    [aux_sym_number_token1] = ACTIONS(81),
    [aux_sym_number_token2] = ACTIONS(81),
    [aux_sym_number_token3] = ACTIONS(83),
    [sym_string] = ACTIONS(81),
    [sym_char_literal] = ACTIONS(81),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(81),
    [anon_sym_DOT_DOT] = ACTIONS(83),
    [anon_sym_LT_LT] = ACTIONS(81),
    [anon_sym_GT_GT] = ACTIONS(81),
    [anon_sym_EQ_EQ] = ACTIONS(81),
    [anon_sym_BANG_EQ] = ACTIONS(81),
    [anon_sym_LT_EQ] = ACTIONS(81),
    [anon_sym_GT_EQ] = ACTIONS(81),
    [anon_sym_PLUS_EQ] = ACTIONS(81),
    [anon_sym_DASH_EQ] = ACTIONS(81),
    [anon_sym_STAR_EQ] = ACTIONS(81),
    [anon_sym_SLASH_EQ] = ACTIONS(81),
    [anon_sym_PERCENT_EQ] = ACTIONS(81),
    [anon_sym_AMP_AMP] = ACTIONS(81),
    [anon_sym_PIPE_PIPE] = ACTIONS(81),
    [anon_sym_DASH_GT] = ACTIONS(81),
    [anon_sym_EQ_GT] = ACTIONS(81),
    [anon_sym_PLUS] = ACTIONS(83),
    [anon_sym_DASH] = ACTIONS(83),
    [anon_sym_STAR] = ACTIONS(83),
    [anon_sym_SLASH] = ACTIONS(83),
    [anon_sym_PERCENT] = ACTIONS(83),
    [anon_sym_AMP] = ACTIONS(83),
    [anon_sym_PIPE] = ACTIONS(83),
    [anon_sym_CARET] = ACTIONS(81),
    [anon_sym_TILDE] = ACTIONS(81),
    [anon_sym_BANG] = ACTIONS(83),
    [anon_sym_LT] = ACTIONS(83),
    [anon_sym_GT] = ACTIONS(83),
    [anon_sym_EQ] = ACTIONS(83),
    [anon_sym_LPAREN] = ACTIONS(81),
    [anon_sym_RPAREN] = ACTIONS(81),
    [anon_sym_LBRACE] = ACTIONS(81),
    [anon_sym_RBRACE] = ACTIONS(81),
    [anon_sym_LBRACK] = ACTIONS(81),
    [anon_sym_RBRACK] = ACTIONS(81),
    [anon_sym_COMMA] = ACTIONS(81),
    [anon_sym_SEMI] = ACTIONS(81),
    [anon_sym_COLON] = ACTIONS(81),
    [anon_sym_AT] = ACTIONS(81),
    [anon_sym_DOT] = ACTIONS(83),
    [anon_sym_QMARK] = ACTIONS(81),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_punctuation, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_punctuation, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_reco(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "reco",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
